apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-v1
  labels:
    release: beta
spec:
  replicas: 2
  selector:
    matchLabels:
      release: beta
  template:
    metadata:
      labels:
        release: beta
    spec:
      containers:
      - name: go-101-app
        image: m7dock/go-101-app:v1
        ports:
        - containerPort: 8080
