apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec:
  selector:
    matchLabels:
      app: go-app
      tier: backend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: go-app
        tier: backend
        track: stable
    spec:
      containers:
        - name: go-app
          image: m7dock/go-101-app:v2
          ports:
            - name: http
              containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: go-app-svc
spec:
  selector:
    app: go-app
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: http