---
apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: phantom
  name: phantom
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: phantom
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: phantom
    spec:
      containers:
      - image: m7dock/go-app:latest
        imagePullPolicy: Always
        name: go-app
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---

kind: Service
apiVersion: v1
metadata:
  name: mandrake
spec:
  selector:
    app: phantom
  ports:
    - port: 8080 # Default port for image

